### ISSUE TITLE
Keyboard does not work

### ISSUE THREAD

**Issue by AxelAhlborn** [rpsubc8/ESP32TinyEmudore#1]
TTGO VGA 1.4, Keyboard and mouse installed. Keyboard does not work. Greetings Axel

**Comment by rpsubc8** [comment]
It is explained in the documentation that this test version does not use the PS/2 keyboard, but a remote UART keyboard, i.e. from the VStudio debug console or COMx telnet (putty):
[https://www.putty.org](https://www.putty.org)

**Comment by AxelAhlborn** [comment]
Ok, so you must connect the USB Device to the Computer and then you can use Putty. Thank you for the information. Greetings Axel
